name: whitedoor
favicon: null
layout_spectrum: 0.99904
typography_spectrum: 0.51521
title: Recent Events @ White Door
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b1adae'
    - '#604d3c'
    - '#e9d2cc'
    - '#6c7a85'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
