name: whitedoor
favicon: null
layout_spectrum: 0.97435
typography_spectrum: 0.54007
title: Recent Events @ White Door
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#e5e5e5'
    - '#3c3c3c'
    - '#646464'
    - '#a5a5a5'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.4529909563716501
purpose: []
