name: whitedoor
favicon: null
layout_spectrum: 0.4638992790132761
typography_spectrum: 0.27625378500670195
title: Recent Events @ White Door
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8270943278912455
  lightness: 0.46186126046814024
  saturation: 0.4376292871311307
  rhythmicContrast: 0.4529909563716501
purpose: []
